/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Datos;
import clases.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUISFERNANDO
 */
public class frmUsuarios extends javax.swing.JInternalFrame {
    
    private Datos misDatos;
    private int usuAct = 0;
    private boolean nuevo = false;
    private DefaultTableModel miTabla;
    
   public void setDatos(Datos misDatos) {
       this.misDatos = misDatos;
      
   }
    public frmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmacion = new javax.swing.JPasswordField();
        cmbPerfil = new javax.swing.JComboBox();
        btnPrimero = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID Usuario*:");

        txtIDUsuario.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtIDUsuario.setEnabled(false);

        jLabel2.setText("Nombres*:");

        txtNombres.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtNombres.setEnabled(false);

        jLabel3.setText("Apellidos*:");

        txtApellidos.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtApellidos.setEnabled(false);

        jLabel4.setText("Clave*:");

        txtClave.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txtClave.setEnabled(false);

        jLabel5.setText("Confirmación*:");

        txtConfirmacion.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txtConfirmacion.setEnabled(false);

        cmbPerfil.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Perfil", "Administrador", "Empleado" }));
        cmbPerfil.setEnabled(false);
        cmbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilActionPerformed(evt);
            }
        });

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Primero.png"))); // NOI18N
        btnPrimero.setToolTipText("Va al primer registro");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ultimo.png"))); // NOI18N
        btnUltimo.setToolTipText("Va al ultimo registro");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anterior.png"))); // NOI18N
        btnAnterior.setToolTipText("Va al anterior registro");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Siguiente.png"))); // NOI18N
        btnSiguiente.setToolTipText("Va al siguiente registro");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nuevo.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Borrar.png"))); // NOI18N
        btnBorrar.setToolTipText("Eliminar registro");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar registro");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar registro");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar registro");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancelar2.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancela operación");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo3.png"))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("*Campos obligatorios");

        tblTabla.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        jLabel6.setText("Perfil*:");
        jScrollPane2.setViewportView(jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtClave)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConfirmacion))
                            .addComponent(txtApellidos)
                            .addComponent(txtNombres)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIDUsuario)
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo)
                            .addComponent(btnNuevo)
                            .addComponent(btnModificar)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar)
                            .addComponent(btnBorrar)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       //Habilita los botones
        btnPrimero.setEnabled(false);
	btnAnterior.setEnabled(false);
	btnSiguiente.setEnabled(false);
	btnUltimo.setEnabled(false);
	btnNuevo.setEnabled(false);
	btnModificar.setEnabled(false);
	btnGuardar.setEnabled(true);
	btnCancelar.setEnabled(true);
	btnBorrar.setEnabled(false);
	btnBuscar.setEnabled(false);
        
        //Habilita los campos
        txtIDUsuario.setEnabled(true);
	cmbPerfil.setEnabled(true);
	txtNombres.setEnabled(true);
	txtApellidos.setEnabled(true);
	txtClave.setEnabled(true);
	txtConfirmacion.setEnabled(true);
        
        //Limpia los campos
        txtIDUsuario.setText("");
	txtNombres.setText("");
	txtApellidos.setText("");
	txtClave.setText("");
	txtConfirmacion.setText("");
	cmbPerfil.setSelectedIndex(0);
        
        //Activamos el flag del registro nuevo
        nuevo = true;
        
        //Dar foco al ID
        txtIDUsuario.requestFocusInWindow();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                if(txtIDUsuario.getText().equals("")) {
			JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID de usuario");
			txtIDUsuario.requestFocusInWindow();
			return; 
		}
		
		if(cmbPerfil.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un perfil de usuario");
			cmbPerfil.requestFocusInWindow();
			return; 
		}
		
		if(txtNombres.getText().equals("")) {
			JOptionPane.showMessageDialog(rootPane,"Debe ingresar un nombre(s) de usuario" );
			txtNombres.requestFocusInWindow();
			return; 
		}
		
		if(txtApellidos.getText().equals("")) {
			JOptionPane.showMessageDialog(rootPane,"Debe ingresar un apellido(s) de usuario" );
			txtApellidos.requestFocusInWindow();
			return; 
		}
		
		String clave = new String(txtClave.getPassword());
		String confirmacion = new String(txtConfirmacion.getPassword());
		
		if(clave.equals("")) {
			JOptionPane.showMessageDialog(rootPane,"Debe ingresar una clave de usuario" );
			txtClave.requestFocusInWindow();
			return; 
		}
		
		if(confirmacion.equals("")) {
			JOptionPane.showMessageDialog(rootPane,"Debe ingresar una confirmación de la clave del usuario" );
			txtConfirmacion.requestFocusInWindow();
			return;
		}
		
		if(!clave.equals(confirmacion)) {
			JOptionPane.showMessageDialog(rootPane,"La clave y la confirmación no concuerdan");
			txtClave.setText("");
			txtConfirmacion.setText("");
			txtClave.requestFocusInWindow();
			return;
                }
                
                //Si es nuevo validamos que el usuario no exista
                int pos = misDatos.posicionUsuario(txtIDUsuario.getText());
                if(nuevo) {
			if(pos != -1) {
				JOptionPane.showMessageDialog(rootPane,"El usuario ya existe");
				txtIDUsuario.requestFocusInWindow();
				return;
			}
                        
                     }

   
                      else {
                            if(pos == -1) {
				JOptionPane.showMessageDialog(rootPane,"El usuario no existe");
				txtIDUsuario.requestFocusInWindow();
				return;
                        }
		}
                
//Creamos el objeto usuario y os agragamos a datos
                Usuario miUsuario = new Usuario(
			txtIDUsuario.getText(),
			txtNombres.getText(),
			txtApellidos.getText(),
			clave,
			cmbPerfil.getSelectedIndex());
                
                String msg ;
		if(nuevo) {
			msg = misDatos.agregarUsuario(miUsuario);
		} else {
			msg = misDatos.modificarUsuario(miUsuario , pos);
		}	
                
               
		JOptionPane.showMessageDialog(rootPane,msg);
		

//Desabilita los botones
        btnPrimero.setEnabled(true);
	btnAnterior.setEnabled(true);
	btnSiguiente.setEnabled(true);
	btnUltimo.setEnabled(true);
	btnNuevo.setEnabled(true);
	btnModificar.setEnabled(true);
	btnGuardar.setEnabled(false);
	btnCancelar.setEnabled(false);
	btnBorrar.setEnabled(true);
	btnBuscar.setEnabled(true);
        
        //Desabilitar los campos
        txtIDUsuario.setEnabled(false);
	cmbPerfil.setEnabled(false);
	txtNombres.setEnabled(false);
	txtApellidos.setEnabled(false);
	txtClave.setEnabled(false);
	txtConfirmacion.setEnabled(false);
        
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Desabilita los botones
        btnPrimero.setEnabled(true);
	btnAnterior.setEnabled(true);
	btnSiguiente.setEnabled(true);
	btnUltimo.setEnabled(true);
	btnNuevo.setEnabled(true);
	btnModificar.setEnabled(true);
	btnGuardar.setEnabled(false);
	btnCancelar.setEnabled(false);
	btnBorrar.setEnabled(true);
	btnBuscar.setEnabled(true);
        
        //Desabilitar los campos
        txtIDUsuario.setEnabled(false);
	cmbPerfil.setEnabled(false);
	txtNombres.setEnabled(false);
	txtApellidos.setEnabled(false);
	txtClave.setEnabled(false);
	txtConfirmacion.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
          //Habilita los botones
        btnPrimero.setEnabled(false);
	btnAnterior.setEnabled(false);
	btnSiguiente.setEnabled(false);
	btnUltimo.setEnabled(false);
	btnNuevo.setEnabled(false);
	btnModificar.setEnabled(false);
	btnGuardar.setEnabled(true);
	btnCancelar.setEnabled(true);
	btnBorrar.setEnabled(false);
	btnBuscar.setEnabled(false);
        
        //Habilita los campos
	cmbPerfil.setEnabled(true);
	txtNombres.setEnabled(true);
	txtApellidos.setEnabled(true);
	txtClave.setEnabled(true);
	txtConfirmacion.setEnabled(true);
        
        //desactivamos el flag del registro nuevo
        nuevo = false;
        
        //Dar foco al ID
        txtNombres.requestFocusInWindow();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
                mostrarRegistro();
                llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
                 usuAct = 0;
		mostrarRegistro();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        	usuAct = misDatos.numeroUsuarios() -1;
		mostrarRegistro();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        usuAct ++;
        if(usuAct == misDatos.numeroUsuarios()) {
		usuAct = 0;
		
		}
        	mostrarRegistro();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        usuAct --;
        if(usuAct == - 1){
          usuAct = misDatos.numeroUsuarios()-1;
		
		}
        	mostrarRegistro();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de borrar el registro");
	if(rta != 0) {
            return; 
	}
		
		String msg; 
                msg = misDatos.borrarUsuario(usuAct);
		JOptionPane.showMessageDialog(rootPane, msg);
                usuAct = 0;
                mostrarRegistro();        
		llenarTabla(); 
			
	
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     String usuario = JOptionPane.showInputDialog("Ingrese ID de usuario");
		if(usuario.equals("")) {
			return;
		}
			 
		int pos = misDatos.posicionUsuario(usuario);
		if(pos == -1) {
			JOptionPane.showMessageDialog(rootPane, "Usuario no existe");
			return;
		}
		
		usuAct = pos;
		mostrarRegistro();
        
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void mostrarRegistro() {
	txtIDUsuario.setText(misDatos.getUsuarios()[usuAct].getIdUsuario());
	cmbPerfil.setSelectedIndex(misDatos.getUsuarios()[usuAct].getPerfil());
	txtNombres.setText(misDatos.getUsuarios()[usuAct].getNombres());
	txtApellidos.setText(misDatos.getUsuarios()[usuAct].getApellidos());
	txtClave.setText(misDatos.getUsuarios()[usuAct].getClave());
	txtConfirmacion.setText(misDatos.getUsuarios()[usuAct].getClave());
    }
    
    private void llenarTabla() {
		String titulos[] = {"ID Usuario", "Perfil", "Nombres", "Apellidos"};
		String registro[] = new String[4];
		miTabla = new DefaultTableModel(null, titulos);
		
		for(int i = 0; i < misDatos.numeroUsuarios(); i++) {
			registro[0] = misDatos.getUsuarios()[i].getIdUsuario();
			registro[1] = perfil(misDatos.getUsuarios()[i].getPerfil());
			registro[2] = misDatos.getUsuarios()[i].getNombres();
			registro[3] = misDatos.getUsuarios()[i].getApellidos();
			miTabla.addRow(registro);
		}
		
		tblTabla.setModel(miTabla);
    }   
    
    private String perfil(int idPerfil) {
        if(idPerfil == 1) return "Administrador";
        else 
            return "Empleado";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cmbPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
